### ISSUE TITLE
`--exclude` does not exclude files specified directly

### ISSUE THREAD

**Issue by mrazauskas** [wellwelwel/poku#608] opened 2024-07-26 12:45 UTC
Might be I misunderstood what `--exclude` does.

If there are several test files and `one.test.js` between them. I though it will not be included in the test run with the following command:

```shell
npx poku **/*.test.* --exclude='one'
```

**Comment by wellwelwel** [comment] 2024-07-26 13:02
I'll take a closer look. In theory, if the exclude passes the Regex `test`, it doesn't pass through the filter and continues recursion:

https://github.com/wellwelwel/poku/blob/e3bc2cfaad1d6014f4f81b2bf6b862d2c1b489b9/src/modules/helpers/list-files.ts#L69-L79

Possibly the problem is using `return` instead of `continue`.

**Comment by mrazauskas** [comment] 2024-07-26 13:07
Hm.. The same with `---filter`. The following runs `two.test.js`, but I though only `one.test.js` will be selected:

```shell
npx poku **/*.test.* --filter='one' 
```

But it seems like they both work well if a test is selected from a directory path. Like this:

```
npx poku ./tests --filter='one' 
```

Also this is how they are documented. So perhaps that’s intentional?

**Comment by wellwelwel** [comment] 2024-07-26 13:12
> Also this is how they are documented. So perhaps that’s intentional?

I've never tried using it as a `glob`. Since the retrieval is done using `readdir`, I didn't expect it to be compatible with this pattern (that's why I didn't close issue #555).

**Comment by wellwelwel** [comment] 2024-07-26 13:17
The default behavior is to retrieve all `*.test.*` and `*.spec.*` files, while `readdir` brings absolutely all files in the selected paths, them `filter` and `exclude` sort out who should and shouldn't be tested (which would lead to the issue #590).

**Comment by mrazauskas** [comment] 2024-07-26 13:23
There is no glob (; For instance, if only two files (`one.test.js` and `two.test.js`) are in the directory, both of the following commands will reach `process.argv.slice(2)` as `["one.test.js", "two.test.js"]`:

```shell
npx poku *.test.*
npx poku one.test.js two.test.js
```

The following runs both files:

```shell
npx poku one.test.js two.test.js --exclude='one'
```

But this works as expected (i.e. it skips `one.test.js`):

```
npx poku . --exclude='one'
```

**Comment by wellwelwel** [comment] 2024-07-26 13:29
Ohh... I think I get the problem now.

If `npx` is who's bring the files. When a file is passed directly, then it doesn't use the `listFile` method:

https://github.com/wellwelwel/poku/blob/e3bc2cfaad1d6014f4f81b2bf6b862d2c1b489b9/src/services/run-tests.ts#L25-L30

---

In this case, this really is the expected behavior.

**Comment by wellwelwel** [comment] 2024-07-26 13:36
Do you think this should be treated as an issue (filtering directly specified files too)?

**Comment by mrazauskas** [comment] 2024-07-26 13:47
Hm.. In a way current implementation is treating directory and file paths differently. For a user these are just paths. Also being able to run `poku tests/*.test.* --exclude='one'` is a powerful feature.

Another aspect. `exclude` can be specified in the config file. In this context `poku tests/api-*` and `poku ./tests` will select files differently, because first command will not take into account the `exclude`. Anything can be excluded. For example: `exclude: "fixture"`. So I would say, it should be always excluded.

Just think out loud (;

**Comment by wellwelwel** [comment] 2024-07-26 13:49
Thanks! I'll consider it a bug 🙋🏻‍♂️

**Comment by wellwelwel** [comment] 2024-07-27 22:32
Fixed in https://github.com/wellwelwel/poku/commit/de9d8171a181f9bd6dc0806321a7f1a029b1fd0b.

**Closed by wellwelwel** 2024-07-27 22:32 UTC
Labels: bug, list files, priority
